nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
  - lang_code: es
    model_name: es_core_news_md
  - lang_code: fr
    model_name: fr_core_news_sm
  - lang_code: it
    model_name: it_core_news_md
  - lang_code: pl
    model_name: pl_core_news_lg
  - lang_code: kr
    model_name: ko_core_news_lg
  - lang_code: th
    model_name: xx_ent_wiki_sm


ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME
    # ja_core_news_lg
    PHONE: PHONE_NUMBER
    # ko_core_news_lg. No reference. Tested manually.
    DT: DATE_TIME 
    LC: LOCATION
    OG: ORGANIZATION
    PS: PERSON
    TI: DATE_TIME
    QT: QUANTITY
    # nb_core_news_lg https://github.com/ltgoslo/norne?tab=readme-ov-file#entity-definitions
    EVT: EVENT
    GPE_LOC: LOCATION
    GPE_ORG: ORGANIZATION
    PROD: PRODUCT
    # pl_core_news_lg https://github.com/CLARIN-PL/PolDeepNer?tab=readme-ov-file#about
    date: DATE_TIME
    geogName: LOCATION
    orgName: ORGANIZATION
    persName: PERSON
    placeName: LOCATION
    time: DATE_TIME
    # sv_core_news_lg. No reference. Tested manually. 
    PRS: PERSON
    TME: DATE_TIME
    WRK: WORK_OF_ART

  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
  -
  labels_to_ignore:
  - ORGANIZATION # Has many false positives
  - CARDINAL
  - EVENT
  - LANGUAGE
  - LAW
  - MONEY
  - ORDINAL
  - PERCENT
  - PRODUCT
  - QUANTITY
  - WORK_OF_ART
  - MISC # Miscellaneous. Entities which do not belong to the other categories. Animals species for example.
  # ja_core_news_lg
  - MOVEMENT # unknown
  - PET_NAME
  - TITLE_AFFIX # secondary title
  # nb_core_news_lg
  - DRV # Derived. Words derived from a name, but not a name themselves. "NewYorker" for example.
  # sv_core_news_lg
  - MSR # MEASURE (similar to quantity)
  - ENV # unknown, most likely EVENT
  - OBJ # unknown, most likely OBJECT
